{% set name = "swifter" %}
{% set version = "1.1.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/swifter-{{ version }}.tar.gz
  sha256: 120efa94d7bbc8ef5fc5d407db97f69fd39800ad3d93ab7e6ba64037b4fdfcc3

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - bleach >=3.1.1
    - cloudpickle >=0.2.2
    - dask >=2.10.0
    - ipywidgets >=7.0.0
    - pandas >=1.0.0
    - parso >0.4.0
    - psutil >=5.6.6
    - python >=3.6
    - tqdm >=4.33.0

test:
  imports:
    - swifter
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/jmcarpenter2/swifter
  summary: A package which efficiently applies any function to a pandas dataframe or series in the fastest available manner
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jmcarpenter2
    - apcamargo
