{% set name = "swifter" %}
{% set version = "0.301" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 89c3581d35beba86a1e2e348cf4f6d8ba251b117f347bd4fb8191e21760acac9

build:
  number: 0
  skip: True  # [py27]
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "

requirements:
  host:
    - pip
    - python
  run:
    - dask >=0.19.0
    - ipywidgets >=7.0.0
    - numba
    - pandas >=0.23.0
    - psutil
    - python
    - tqdm >=4.33.0
    - parso >0.4.0

test:
  imports:
    - swifter

about:
  home: https://github.com/jmcarpenter2/swifter
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: "A package which efficiently applies any function to a pandas dataframe or series in the fastest available manner."

extra:
  recipe-maintainers:
    - apcamargo
