travis:
  secure:
    BINSTAR_TOKEN: yb3kkvKS7y41Uj10LJi9/UXS1zIn85sCttQiUnRw8RQzHd+FhoYfdNDDTaqujMmefQDnCNNr6mobph98i1mDylTyVa8szUHEwKwB4aTcEC2GuJoC8DfAv6lAJCE45rSzcbtXfe7A3imVggZ3Y93OfdJKWplXq5y3uIFz6O8mXRVBnHvNwewi+WWgy0ToaeNFrpfLky1cYGyMk5npJV80J+0XvEdjsdwLhiX5syfmT7X26hcSe5alK5VLHSQBnPpH7SpIc4qQfrR+izwgpITT2A/BiQBn4rcDULpbtU4+wT1BiNrIHUUNRo13a/yVAr4PgRZtPqFD2WSLsoVHpba23HALBX3tOrq/iZW6ftx5AuH5M+KSvdCKa8gsZyinfiIQTZN4agp6jguC/W+y+bCpGdsJsOYnHWzSLcL4ccwNzA92IEoclWzSZNvpM6uec4SV1aCvwbT3ZN2wEaNOsk3rZEk6rZdLDvcvR6w1iAo+tbJHXdKIbWtfS6yKYAnQ9VTw7Cokrakjf1mysel8LgiCTjhVsTpdbuuorgaG5mAMr2sGn4Le1Y+DFeLzWeFRwroO9oa5fgqFF6WnnDizUSHEzQbgamvebOeR2/Jw8/Czvyf0Y60PLqeUqpZHY/Dz4Bjy0EfmfLUU5D3+44iMOENCm5XGG6pDe+wI0Y+xtMmDr5k=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
provider:
  win: azure
conda_forge_output_validation: false
